Default: &defaults
  user: metoo
  password: metoo
  host: localhost
  port: 5432
  database: metoo
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: metoo_test
  <<: *defaults

Staging:
  database: metoo_staging
  poolsize: 100
  <<: *defaults

Production:
  database: metoo_production
  poolsize: 100
  <<: *defaults